version: "3.5"
services:
  node:
    container_name: picpay_node
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 19000:19000
      - 19001:19001
      - 19006:19006
      - 19002:19002
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 
